"""Constants for the Sagemcom DSIW74 integration."""

DOMAIN = "dsiw74"
DEFAULT_NAME = "DSIW74"
DEFAULT_PORT = 3030
DEFAULT_TIMEOUT = 5

CONF_ENCODER_URL = "encoder_url"
DEFAULT_ENCODER_URL = "http://192.168.0.14"
CONF_CHANNEL_PRESETS = "channel_presets"
CONF_MEDIA_PLAYER_ENTITY = "media_player_entity"
CONF_AUTO_SYNC_CHANNEL = "auto_sync_channel"
DEFAULT_AUTO_SYNC_CHANNEL = True

RAW_COMMANDS = {
    "KeyAt",
    "KeyBack",
    "KeyBlue",
    "KeyDown",
    "KeyEight",
    "KeyExit",
    "KeyFForward",
    "KeyFive",
    "KeyFour",
    "KeyGreen",
    "KeyGuide",
    "KeyInfo",
    "KeyLang",
    "KeyLeft",
    "KeyMenu",
    "KeyMode",
    "KeyMute",
    "KeyNine",
    "KeyOK",
    "KeyOPTS",
    "KeyOne",
    "KeyPause",
    "KeyPlay",
    "KeyProgramDown",
    "KeyProgramUp",
    "KeyRecList",
    "KeyRecord",
    "KeyRed",
    "KeyRewind",
    "KeyRight",
    "KeySetup",
    "KeySeven",
    "KeySix",
    "KeyStandBy",
    "KeyStop",
    "KeyTVRadio",
    "KeyThree",
    "KeyTwo",
    "KeyUp",
    "KeyVOD",
    "KeyVolumeDown",
    "KeyVolumeUp",
    "KeyYellow",
    "KeyZero",
}

COMMAND_ALIASES = {
    "power": "KeyStandBy",
    "standby": "KeyStandBy",
    "menu": "KeyMenu",
    "exit": "KeyExit",
    "back": "KeyBack",
    "guide": "KeyGuide",
    "epg": "KeyGuide",
    "info": "KeyInfo",
    "up": "KeyUp",
    "down": "KeyDown",
    "left": "KeyLeft",
    "right": "KeyRight",
    "ok": "KeyOK",
    "channel_up": "KeyProgramUp",
    "ch+": "KeyProgramUp",
    "channel_down": "KeyProgramDown",
    "ch-": "KeyProgramDown",
    "volume_up": "KeyVolumeUp",
    "vol+": "KeyVolumeUp",
    "volume_down": "KeyVolumeDown",
    "vol-": "KeyVolumeDown",
    "mute": "KeyMute",
    "0": "KeyZero",
    "1": "KeyOne",
    "2": "KeyTwo",
    "3": "KeyThree",
    "4": "KeyFour",
    "5": "KeyFive",
    "6": "KeySix",
    "7": "KeySeven",
    "8": "KeyEight",
    "9": "KeyNine",
    "red": "KeyRed",
    "green": "KeyGreen",
    "yellow": "KeyYellow",
    "blue": "KeyBlue",
    "play": "KeyPlay",
    "pause": "KeyPause",
    "stop": "KeyStop",
    "record": "KeyRecord",
    "rewind": "KeyRewind",
    "fast_forward": "KeyFForward",
    "ff": "KeyFForward",
    "vod": "KeyVOD",
    "recordings": "KeyRecList",
    "rec_list": "KeyRecList",
    "tv_radio": "KeyTVRadio",
    "language": "KeyLang",
    "lang": "KeyLang",
    "options": "KeyOPTS",
    "opts": "KeyOPTS",
    "setup": "KeySetup",
    "mode": "KeyMode",
    "at": "KeyAt",
}
